### ISSUE TITLE
virtualenvwrapper isn't listed as a dependency

### ISSUE THREAD

**Issue by zevav** [andersoncardoso/pyenv-autoenv#7]

**Comment by zevav** [comment]
(neither is pyenv-virtualenvwrapper; is it a dependency?)

**Comment by andersoncardoso** [comment]
Hi, 

sorry for the late answer.
I added a mention to virtualenvwrapper on the readme. 
The `pyenv-virtualenvwrapper` is not a dep.
Thanks for the report

cheers
